# Generated by Django 5.0.6 on 2024-07-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='data_all',
            old_name='position',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='data_all',
            old_name='class_name',
            new_name='type_name',
        ),
    ]
