# Generated by Django 5.0.6 on 2024-07-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0002_rename_model_type_name_rename_position_data_all_pos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='departments',
        ),
        migrations.RenameModel(
            old_name='type_name',
            new_name='type_names',
        ),
    ]
