# Generated by Django 5.0.6 on 2024-07-10 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0003_rename_department_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='number',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='old_depart',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='old_ip',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='old_position',
        ),
        migrations.AddField(
            model_name='edit_log',
            name='changes',
            field=models.TextField(default='空'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit_log',
            name='instance_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit_log',
            name='model_name',
            field=models.CharField(default='空', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit_log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data_all',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='data_all',
            name='descr',
            field=models.TextField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='data_all',
            name='pos',
            field=models.CharField(max_length=20, verbose_name='位置'),
        ),
    ]
