# Generated by Django 5.0.6 on 2024-07-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0004_remove_edit_log_date_remove_edit_log_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_log',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='instance_id',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='edit_log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='edit_log',
            name='edit_changes',
            field=models.CharField(default='', max_length=100, verbose_name='变更值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit_log',
            name='edit_models',
            field=models.CharField(default='', max_length=50, verbose_name='更改类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit_log',
            name='edit_number',
            field=models.CharField(default='', max_length=18, verbose_name='资产编号'),
            preserve_default=False,
        ),
    ]
