# Generated by Django 5.0.6 on 2024-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0005_remove_edit_log_changes_remove_edit_log_instance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_log',
            name='edit_changes',
            field=models.TextField(verbose_name='变更值'),
        ),
    ]
