# Generated by Django 5.0.6 on 2024-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0006_alter_edit_log_edit_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_log',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='edit_log',
            name='edit_models',
            field=models.CharField(max_length=12, verbose_name='更改类型'),
        ),
    ]
