# Generated by Django 5.0.6 on 2024-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0009_edit_log_new_depart_edit_log_old_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all',
            name='ip',
            field=models.GenericIPAddressField(default='', null=True, protocol='ipv4'),
        ),
    ]
