# Generated by Django 5.0.6 on 2024-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0010_alter_data_all_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all',
            name='model',
            field=models.CharField(max_length=25, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='data_all',
            name='pos',
            field=models.CharField(max_length=25, verbose_name='位置'),
        ),
    ]
