# Generated by Django 5.0.6 on 2024-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0011_alter_data_all_model_alter_data_all_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='', null=True, protocol='ipv4'),
        ),
    ]
