# Generated by Django 5.0.6 on 2024-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zcglxt', '0012_alter_data_all_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all',
            name='descr',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='data_all',
            name='pos',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='摆放位置'),
        ),
    ]
